$(".banner1").banner({
    imgs:$(".banner1").find("img"),
    left:$(".banner1").find("#left"),
    right:$(".banner1").find("#right"),
    list:true,
    autoPlay:true,
    delayTime:2000,
    moveTime:200
})